export type GameState = {
	phase: GamePhase;
	round: number;
	currentHostId: string;
	activeGuesserId: string;
	letters: LetterHint[];
	wrongChars: string[];
	configuration: {
		autoGeneratedWords: boolean;
		minWordLength: number;
		maxWordLength: number;
	};
};

export type GamePhase = 'spelling' | 'guessing' | 'waiting';
export type LetterHint = null | string;

export type PlayerGuessedEventData = {
	char: string;
};

export type PlayerSubmittedWordEventData = {
	word: string;
};
