export type GameState = {
	phase: GamePhase;
	round: number;
	currentHostId: string;
	activeGuesserId: string;
	letters: LetterHint[];
	wrongChars: string[];
	configuration: HangmanConfiguration;
	scoreboard: HangmanScoreboard;
};

export type HangmanConfiguration = {
	autoGeneratedWords: boolean;
	minWordLength: number;
	maxWordLength: number;
	scoreWinningThreshold: number;
	turnWinningThreshold: number;
	maxWrongGuesses: number;
};

export type GamePhase = 'spelling' | 'guessing' | 'waiting' | 'finished';
export type LetterHint = null | {
	value: string;
	state: 'guessed' | 'gameover';
};

export type HangmanScoreboard = HangmanScoreboardItem[];
export type HangmanScoreboardItem = {
	playerId: string;
	points: number;
};

export type PlayerGuessedEventData = {
	char: string;
};

export type PlayerSubmittedWordEventData = {
	word: string;
};
