import React, { ReactNode } from 'react';
import ModuleGameInterface from '../../framework/modules/ModuleGameInterface';
import ModuleApi from '../../framework/modules/ModuleApi';
import hangman from './Hangman';
import { GameState } from '@edelgames/types/src/modules/hangman/HMTypes';
import { EventDataObject } from '@edelgames/types/src/app/ApiTypes';
import GameWheel from './components/gameWheel/GameWheel';
import Scoreboard from './components/scoreboard/Scoreboard';
import InputField from './components/inputField/InputField';

interface IState {
	gameState: GameState;
}

export default class Hangman
	extends React.Component<{}, IState>
	implements ModuleGameInterface
{
	private readonly api: ModuleApi;

	state: IState = {
		gameState: {
			phase: 'waiting',
			round: 0,
			activeGuesserId: '',
			currentHostId: '',
			letters: [],
			wrongChars: [],
			configuration: {
				minWordLength: 1,
				maxWordLength: 1,
				autoGeneratedWords: false,
			},
		},
	};

	constructor(props: {}) {
		super(props);
		this.api = new ModuleApi(hangman, this);
		this.api
			.getEventApi()
			.addEventHandler(
				'gameStateUpdated',
				this.onGameStateUpdateReceived.bind(this)
			);
	}

	componentDidMount() {}

	componentWillUnmount() {}

	onGameStateUpdateReceived(eventData: EventDataObject): void {
		const newState = eventData as GameState;

		this.setState(
			{
				gameState: {
					phase: newState.phase,
					round: newState.round,
					activeGuesserId: newState.activeGuesserId,
					currentHostId: newState.currentHostId,
					letters: newState.letters,
					wrongChars: newState.wrongChars,
					configuration: newState.configuration,
				},
			},
			console.log.bind(null, newState)
		);
	}

	render(): ReactNode {
		const activePlayerId = this.state.gameState.phase === 'spelling' ?
			this.state.gameState.currentHostId :
			this.state.gameState.activeGuesserId;


		return (
			<div id={'hangman'}>
				<GameWheel
					letters={this.state.gameState.letters}
					playerApi={this.api.getPlayerApi()}
					activePlayerId={activePlayerId}
				/>

				<div className={'game-data-interface'}>
					<Scoreboard />

					<InputField
						playerApi={this.api.getPlayerApi()}
						eventApi={this.api.getEventApi()}
						gameState={this.state.gameState}
						playerGuessCharCallback={console.log}
						playerGuessWordCallback={console.log}
					/>
				</div>
			</div>
		);
	}
}