import {
	ColorGrid,
	GridColorOptions,
} from '@edelgames/types/src/modules/colorChecker/CCTypes';

export const defaultGrid: ColorGrid = [
	[
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: true, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: true, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: true, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: true, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: true, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: true, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: true, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.GREEN, isSpecial: true, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: true, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: true, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: true, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.ORANGE, isSpecial: true, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: true, checked: false },
	],
	[
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: true, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
	],
	[
		{ color: GridColorOptions.YELLOW, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.GREEN, isSpecial: false, checked: false },
		{ color: GridColorOptions.BLUE, isSpecial: false, checked: false },
		{ color: GridColorOptions.RED, isSpecial: false, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: true, checked: false },
		{ color: GridColorOptions.ORANGE, isSpecial: false, checked: false },
	],
];
